server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 56726188337-5nb4qpnckkgj39bhtrq6nk8r8eurr4dc.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
          github:
            client-id: Ov23liODZZRCALYKfJjL
            client-secret: 5191f5da44b0689b6b1565bbd03ac7c46f700107
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - read:user
              - user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
